// Turns home-src/index.html into lib/home-html.ts so the homepage ships inside the server
// bundle and needs no file reads at runtime. The FAQ structured data is generated from the
// visible question cards, so what search engines and AI assistants read can never drift
// from what visitors see.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
let html = readFileSync(path.join(root, "home-src", "index.html"), "utf8");

const decode = (s) =>
  s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
const text = (s) => decode(s.replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();

const faq = [];
for (const m of html.matchAll(/<article class="fq">([\s\S]*?)<\/article>/g)) {
  const q = /<h3>([\s\S]*?)<\/h3>/.exec(m[1]);
  const a = /<p>([\s\S]*?)<\/p>/.exec(m[1]);
  if (q && a) faq.push({ q: text(q[1]), a: text(a[1]) });
}
if (faq.length < 3) throw new Error("build-home: expected the FAQ cards in home-src/index.html");

const entity = JSON.stringify({
  "@type": "FAQPage",
  "@id": "https://omnistacksdigital.com/#faq",
  mainEntity: faq.map(({ q, a }) => ({
    "@type": "Question",
    name: q,
    acceptedAnswer: { "@type": "Answer", text: a },
  })),
});
if (!html.includes("<!--FAQ-LD-->")) throw new Error("build-home: FAQ placeholder missing");
// the JSON-LD "</" sequence is escaped so it can never close the script tag early
html = html.replace("<!--FAQ-LD-->", entity.replace(/</g, "\\u003c"));

writeFileSync(
  path.join(root, "lib", "home-html.ts"),
  `// Generated by scripts/build-home.mjs from home-src/index.html. Do not edit by hand.\nexport const HOME_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`home-html.ts written: ${html.length} bytes, ${faq.length} FAQ entries`);
